### ISSUE TITLE
When External is selected for time, Input A is directly output to Time out, instead of mix of ext in's or slider values. 

### ISSUE THREAD

**Issue by waldnzwrld** [wir35/marf#19] opened 2022-06-29 03:28 UTC
I'm testing things out, 

Current configuration: 

AFG2 is running a 4 step sequence, all time the same. 

ref out from that sequence is driving a 12 step sequence with stops on every step. 

All time slots are set to external. 

Slow Saw wave input to EXT A

Random voltage 1 from 208 (leftmost) input to any other ext in 

Set half of sliders to A half to other input, check voltage out of Time output it should be an exact copy of whatever is being input to A

![Monosnap 2022-06-28 20-21-58](https://user-images.githubusercontent.com/4338862/176344392-957b025a-268a-456d-8aa8-c5ecc1dbac2d.png)

![Monosnap 2022-06-28 20-23-58](https://user-images.githubusercontent.com/4338862/176344643-0e773731-6419-4728-9f22-36c6480ddc03.png)

![Monosnap 2022-06-28 20-25-39](https://user-images.githubusercontent.com/4338862/176344924-1aa3dcb5-2794-4fe6-b167-fb506dec9800.png)

**Comment by waldnzwrld** [comment] 2022-06-29 03:40
On closer inspection, it appears that only input A is being respected in EXTERNAL mode for time in either AFG and the time value (not just the time output) only respects input A

@maxl0rd

**Comment by maxl0rd** [comment] 2022-07-06 21:26
Thanks for the report.

That PR won't be the relevant any longer since this commit changed the behavior. 
I think that method is actually dead code now.
https://github.com/wir35/marf/commit/b1fb433b453c3aecece552bc35126009d521523b

The correct behavior for your patch is to see the time slider value on the time output, not the ext A signal.

I am going to leave this issue open since I think you might have identified a different problem.

**Comment by maxl0rd** [comment] 2022-07-06 21:29
Also, it's kind of an interesting choice to use the ref out to the start pulse in. Do you find it somehow works better?

The pulse outputs actually have better timing and sharper edges. They should trigger the start interrupts more reliably.

**Comment by waldnzwrld** [comment] 2022-07-11 04:25
> it's kind of an interesting choice to use the ref out to the start pulse in. 

I was just toying around with the timing from the ref out. I'll check for an updated build and let you know if the behavior is as expected, thanks @maxl0rd

**Comment by waldnzwrld** [comment] 2022-07-11 17:51
Things still aren't behaving as expected with the latest release, but are better. 

So the Time output now returns the slider values, but not the sampled value of the external input. 

With a slow Ramp at input A

- Speed of sequence matches the value at input A
- Input B-D are ignored (time sliders do not select external input to sample)
- Time output returns slider values (expect sampled values from external inputs)
- 

With time sliders set like this (all sliders set to external), Random into input B and a slow saw into input A 

![PXL_20220711_175033742.jpg](https://user-images.githubusercontent.com/4338862/178329518-c8d7974d-a00b-4149-ae20-688cb67888e0.jpg)

The time output returns this (Yellow trace Time out, Purple trace Input A)

![PXL_20220711_175047607.jpg](https://user-images.githubusercontent.com/4338862/178329546-7d4a7d0d-1fe1-432d-89a3-738cbe8e049f.jpg)

@maxl0rd

**Comment by maxl0rd** [comment] 2022-07-13 05:29
Excellent report, thanks.

I resolved the problem of not addressing the B-D inputs. That was another misplaced parens.

The time outputs though are working as intended. They are not supposed to relay the external input when set to external. It seems like they should, but that's not how the original works. It is always strictly the level of the time slider.

**Comment by waldnzwrld** [comment] 2022-07-13 15:08
Thanks for the clarification, and for the fix!!! 

You are truly gracing us with your phenomenal work.

**Comment by maxl0rd** [comment] 2022-07-14 03:14
Resolved in beta 5 (marf-v2-66-2022-07-13.hex.zip)

**Closed as completed by maxl0rd** 2022-07-14 03:14 UTC
